apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastzero
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mateussgubim/fastapi-gitops
    targetRevision: HEAD
    path: fastzero 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
