replicaCount: 2

containerPort: 8000

image:
  repository: docker.io/mateuss08/fastzero
  tag: latest

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: fastzero.localhost
      paths:
        - path: /
