replicaCount: 2

containerPort: 8000

image:
  repository: docker.io/mateuss08/fastzero
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-targets: /
  hosts:
    - host: fastzero.local
      paths:
        - path: /

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 75