replicaCount: 2

containerPort: 8000

image:
  repository: docker.io/mateuss08/fastzero
  tag: latest

service:
  type: LoadBalancer
  port: 8000
  targetPort: 8000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: fastzero-service
              port:
                number: 8000
  tls:
  enabled: true
  secretName: fastzero-tls-secret
